[package]
name = "keysym-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
heck = "0.4.0"
regex = "1.5.6"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
